### ISSUE TITLE
#help: Assist AI

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/discord-bot#165]
As talked about in #testers recently :P

**Roadmap:**

- [ ] Discuss the extent of help that the help assist should target to provide,
- [ ] Research the tech needed for implementing it (NLP, how other conversational bots work, etc.),
- [ ] Implement question difficulty gauging, so we could finetune what the bot should be able to answer / attempt to answer,
- [ ] Gather a base dataset of questions to enable testing the followup features,
- [ ] Implement basic questions/replies,
- [ ] Implement some context-aware filler questions/replies,
- [ ] Implement more advanced questions/replies (dealing with specific settings, missing LLE modules, outdated drivers, checking for an issue already existing and being reported at our github/forums),
- [ ] Letting it go in on #help as a separate user, masked as a real user instead of a bot,
- [ ] *Never visiting #help ever again.*

**Comment by dio-gh** [comment]
This was never a particularly serious ticket.
