### ISSUE TITLE
ToDo Items

### ISSUE THREAD

**Issue by 13xforever** [RPCS3/discord-bot#482]
This is just to track what needs to be added in the next update.
- [x] AMD drivers after 19.12+ break OpenGL
- [x] Sly Cooper 4 resolution scaling requires CPU Blit enabled, also needs motion controls
- [x] Make disabled TSX an info instead of a warn
- [x] MSAA warning for 5500/5700 GPUs
- [x] slow cpu warning for all 4 core cpus without TSX
- [x] windows 10 20h2 builds check
